#!/bin/bash
set +e

run_doxygen() {
    # Run doxygen
    REPO_NAME=$1
    ROOT_DOXYGEN_DIR=doxygen/$REPO_NAME

    PKG_NAMES=$2
    # Remove old API folder for the documentation
    if [ -d docs/packages/$REPO_NAME/api ]; then
        rm -rf docs/packages/$REPO_NAME/docs/api
    fi

    mkdir -p docs/packages/$REPO_NAME/docs/api

    for PKG in $PKG_NAMES;
    do
        if [ -d $ROOT_DOXYGEN_DIR/$PKG ]; then 
            rm -rf $ROOT_DOXYGEN_DIR/$PKG
        fi

        echo "Running Doxygen for $PKG"
        echo "Options: GENERATE_XML=YES;GENERATE_HTML=NO;INPUT=$(rospack find $PKG);OUTPUT_DIRECTORY=$ROOT_DOXYGEN_DIR/$PKG"
        mkdir -p $ROOT_DOXYGEN_DIR/$PKG/markdown 
        (cat $ROOT_DOXYGEN_DIR/Doxyfile; 
            echo "DOXYGEN_QUIET=YES"; 
            echo "GENERATE_XML=YES"; 
            echo "GENERATE_HTML=NO"; 
            echo "INPUT=$(rospack find $PKG)"; 
            echo "OUTPUT_DIRECTORY=$ROOT_DOXYGEN_DIR/$PKG") | doxygen -

        moxygen --output $ROOT_DOXYGEN_DIR/$PKG/markdown/api-$PKG.md $ROOT_DOXYGEN_DIR/$PKG/xml

        cp $ROOT_DOXYGEN_DIR/$PKG/markdown/api-$PKG.md docs/packages/$REPO_NAME/docs/api
    done

}

create_readme() {
    TITLE=$1
    REPO_NAME=$2
    OUTPUT_DIR=$3
    IMAGES=$4
    
    echo "# $TITLE" > $OUTPUT_DIR/README.md
    echo "" >> $OUTPUT_DIR/README.md
    cat docs/packages/$REPO_NAME/intro.md >> $OUTPUT_DIR/README.md
    echo "Repository $REPO_NAME README.md update, output_dir=$OUTPUT_DIR"    

    if [ ! -z "$IMAGES" -a "$IMAGES" != " " ]; then
        if [ -d $OUTPUT_DIR/images ]; then
            rm -rf $OUTPUT_DIR/images
        fi

        mkdir $OUTPUT_DIR/images
        for IMAGE in $IMAGES;
        do
            cp docs/packages/$REPO_NAME/images/$IMAGE $OUTPUT_DIR/images
        done
    fi
}

# Run Doxygen on uuv_simulator modules with C++ plugins
run_doxygen "uuv_simulator" "uuv_gazebo_plugins uuv_gazebo_ros_plugins uuv_sensor_ros_plugins uuv_world_plugins uuv_world_ros_plugins"
run_doxygen "uuv_plume_simulator" "uuv_cpc_sensor"

# Build the rest of the documentation
./gen_catkin_pkg_docs --config_file config.yaml

# Copy the intro.md files from each package to the README.md of the repository
create_readme 'RexROV 2' rexrov2 $HOME/catkin_ws/src/rexrov2 "rexrov2.png"
create_readme 'ECA A9 AUV' eca_a9 $HOME/catkin_ws/src/eca_a9 "eca_a9.png"
create_readme 'Desistek SAGA ROV' desistek_saga $HOME/catkin_ws/src/desistek_saga "desistek_saga.png"
create_readme '`uuv_simulator`: Unmanned Underwater Vehicle (UUV) simulation with Gazebo' uuv_simulator $HOME/catkin_ws/src/uuv_simulator ""
create_readme 'Light Autonomous Underwater Vehicle (LAUV) model for Gazebo' lauv_gazebo $HOME/catkin_ws/src/lauv_gazebo "lauv.png"
create_readme 'Plume Simulator' uuv_plume_simulator $HOME/catkin_ws/src/uuv_plume_simulator "plume.png"

# Build the site
mkdocs build
set -e